export const START_INITIAL_GET_CANDIDATE = 'START_INITIAL_GET_CANDIDATE';
export const INITIAL_GET_CANDIDATE_SUCCESS = 'INITIAL_GET_CANDIDATE_SUCCESS';
export const INITIAL_GET_CANDIDATE_ERROR = 'INITIAL_GET_CANDIDATE_ERROR';

export const CREATE_CANDIDATE = 'CREATE_CANDIDATE';
export const CREATE_CANDIDATE_SUCCESS = 'CREATE_CANDIDATE_SUCCESS';
export const CREATE_CANDIDATE_ERROR = 'CREATE_CANDIDATE_ERROR';

export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_ERROR = 'DELETE_CANDIDATE_ERROR';

export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_ERROR = 'UPDATE_CANDIDATE_ERROR';

