export const START_INITIAL_GET_INTERVIEWER = 'START_INITIAL_GET_INTERVIEWER';
export const INITIAL_GET_INTERVIEWER_SUCCESS = 'INITIAL_GET_INTERVIEWER_SUCCESS';
export const INITIAL_GET_INTERVIEWER_ERROR = 'INITIAL_GET_INTERVIEWER_ERROR';

export const CREATE_INTERVIEWER = 'CREATE_INTERVIEWER';
export const CREATE_INTERVIEWER_SUCCESS = 'CREATE_INTERVIEWER_SUCCESS';
export const CREATE_INTERVIEWER_ERROR = 'CREATE_INTERVIEWER_ERROR';

export const DELETE_INTERVIEWER = 'DELETE_INTERVIEWER';
export const DELETE_INTERVIEWER_SUCCESS = 'DELETE_INTERVIEWER_SUCCESS';
export const DELETE_INTERVIEWER_ERROR = 'DELETE_INTERVIEWER_ERROR';

export const UPDATE_INTERVIEWER = 'UPDATE_INTERVIEWER';
export const UPDATE_INTERVIEWER_SUCCESS = 'UPDATE_INTERVIEWER_SUCCESS';
export const UPDATE_INTERVIEWER_ERROR = 'UPDATE_INTERVIEWER_ERROR';

