export const GET_INTERVIEWS = 'GET_INTERVIEWS';
export const GET_INTERVIEWS_SUCCESS = 'GET_INTERVIEWES_SUCCESS';
export const GET_INTERVIEWS_ERROR = 'GET_INTERVIEWS_ERROR';

export const CREATE_INTERVIEW = 'CREATE_INTERVIEW';
export const CREATE_INTERVIEW_SUCCESS = 'CREATE_INTERVIEW_SUCCESS';
export const CREATE_INTERVIEW_ERROR = 'CREATE_INTERVIEW_ERROR';